
# First run this in a separate terminal
# This will run the daemon (you can stop a daemon by doing CTRL + C)
run:
	yarn react-native start

# Then after doing the above command
# in a separate terminal run this command
# make build-ios
build-ios:
	yarn react-native run-ios

lint-fix:
	yarn eslint --fix .

lint:
	yarn eslint .
