module.exports = {
  points: {
    '@context': [
      'https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld',
      {
        wx: 'https://api.weather.gov/ontology#',
        s: 'https://schema.org/',
        geo: 'http://www.opengis.net/ont/geosparql#',
        unit: 'http://codes.wmo.int/common/unit/',
        '@vocab': 'https://api.weather.gov/ontology#',
        geometry: {
          '@id': 's:GeoCoordinates',
          '@type': 'geo:wktLiteral',
        },
        city: 's:addressLocality',
        state: 's:addressRegion',
        distance: {
          '@id': 's:Distance',
          '@type': 's:QuantitativeValue',
        },
        bearing: {
          '@type': 's:QuantitativeValue',
        },
        value: {
          '@id': 's:value',
        },
        unitCode: {
          '@id': 's:unitCode',
          '@type': '@id',
        },
        forecastOffice: {
          '@type': '@id',
        },
        forecastGridData: {
          '@type': '@id',
        },
        publicZone: {
          '@type': '@id',
        },
        county: {
          '@type': '@id',
        },
      },
    ],
    id: 'https://api.weather.gov/points/38.8894,-77.0352',
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [-77.035200000000003, 38.889400000000002],
    },
    properties: {
      '@id': 'https://api.weather.gov/points/38.8894,-77.0352',
      '@type': 'wx:Point',
      cwa: 'LWX',
      forecastOffice: 'https://api.weather.gov/offices/LWX',
      gridX: 96,
      gridY: 70,
      forecast: 'https://api.weather.gov/gridpoints/LWX/96,70/forecast',
      forecastHourly:
        'https://api.weather.gov/gridpoints/LWX/96,70/forecast/hourly',
      forecastGridData: 'https://api.weather.gov/gridpoints/LWX/96,70',
      observationStations:
        'https://api.weather.gov/gridpoints/LWX/96,70/stations',
      relativeLocation: {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [-77.017229, 38.904102999999999],
        },
        properties: {
          city: 'Washington',
          state: 'DC',
          distance: {
            value: 2256.4628420105496,
            unitCode: 'unit:m',
          },
          bearing: {
            value: 223,
            unitCode: 'unit:degrees_true',
          },
        },
      },
      forecastZone: 'https://api.weather.gov/zones/forecast/DCZ001',
      county: 'https://api.weather.gov/zones/county/DCC001',
      fireWeatherZone: 'https://api.weather.gov/zones/fire/DCZ001',
      timeZone: 'America/New_York',
      radarStation: 'KLWX',
    },
  },
  hourly: {
    '@context': [
      'https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld',
      {
        wx: 'https://api.weather.gov/ontology#',
        geo: 'http://www.opengis.net/ont/geosparql#',
        unit: 'http://codes.wmo.int/common/unit/',
        '@vocab': 'https://api.weather.gov/ontology#',
      },
    ],
    type: 'Feature',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'Point',
          coordinates: [-77.024773199999998, 38.888346400000003],
        },
        {
          type: 'Polygon',
          coordinates: [
            [
              [-77.036997299999996, 38.900782700000001],
              [-77.040754800000002, 38.878836499999998],
              [-77.012551900000005, 38.875908500000001],
              [-77.008788700000011, 38.8978544],
              [-77.036997299999996, 38.900782700000001],
            ],
          ],
        },
      ],
    },
    properties: {
      updated: '2020-05-30T23:32:01+00:00',
      units: 'us',
      forecastGenerator: 'HourlyForecastGenerator',
      generatedAt: '2020-05-31T02:28:01+00:00',
      updateTime: '2020-05-30T23:32:01+00:00',
      validTimes: '2020-05-30T17:00:00+00:00/P7DT8H',
      elevation: {
        value: 6.0960000000000001,
        unitCode: 'unit:m',
      },
      periods: [
        {
          number: 1,
          name: '',
          startTime: '2020-05-30T22:00:00-04:00',
          endTime: '2020-05-30T23:00:00-04:00',
          isDaytime: false,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '8 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 2,
          name: '',
          startTime: '2020-05-30T23:00:00-04:00',
          endTime: '2020-05-31T00:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 3,
          name: '',
          startTime: '2020-05-31T00:00:00-04:00',
          endTime: '2020-05-31T01:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 4,
          name: '',
          startTime: '2020-05-31T01:00:00-04:00',
          endTime: '2020-05-31T02:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 5,
          name: '',
          startTime: '2020-05-31T02:00:00-04:00',
          endTime: '2020-05-31T03:00:00-04:00',
          isDaytime: false,
          temperature: 65,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 6,
          name: '',
          startTime: '2020-05-31T03:00:00-04:00',
          endTime: '2020-05-31T04:00:00-04:00',
          isDaytime: false,
          temperature: 63,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 7,
          name: '',
          startTime: '2020-05-31T04:00:00-04:00',
          endTime: '2020-05-31T05:00:00-04:00',
          isDaytime: false,
          temperature: 61,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 8,
          name: '',
          startTime: '2020-05-31T05:00:00-04:00',
          endTime: '2020-05-31T06:00:00-04:00',
          isDaytime: false,
          temperature: 60,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 9,
          name: '',
          startTime: '2020-05-31T06:00:00-04:00',
          endTime: '2020-05-31T07:00:00-04:00',
          isDaytime: true,
          temperature: 59,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 10,
          name: '',
          startTime: '2020-05-31T07:00:00-04:00',
          endTime: '2020-05-31T08:00:00-04:00',
          isDaytime: true,
          temperature: 59,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 11,
          name: '',
          startTime: '2020-05-31T08:00:00-04:00',
          endTime: '2020-05-31T09:00:00-04:00',
          isDaytime: true,
          temperature: 61,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 12,
          name: '',
          startTime: '2020-05-31T09:00:00-04:00',
          endTime: '2020-05-31T10:00:00-04:00',
          isDaytime: true,
          temperature: 63,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 13,
          name: '',
          startTime: '2020-05-31T10:00:00-04:00',
          endTime: '2020-05-31T11:00:00-04:00',
          isDaytime: true,
          temperature: 65,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 14,
          name: '',
          startTime: '2020-05-31T11:00:00-04:00',
          endTime: '2020-05-31T12:00:00-04:00',
          isDaytime: true,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 15,
          name: '',
          startTime: '2020-05-31T12:00:00-04:00',
          endTime: '2020-05-31T13:00:00-04:00',
          isDaytime: true,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 16,
          name: '',
          startTime: '2020-05-31T13:00:00-04:00',
          endTime: '2020-05-31T14:00:00-04:00',
          isDaytime: true,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 17,
          name: '',
          startTime: '2020-05-31T14:00:00-04:00',
          endTime: '2020-05-31T15:00:00-04:00',
          isDaytime: true,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 18,
          name: '',
          startTime: '2020-05-31T15:00:00-04:00',
          endTime: '2020-05-31T16:00:00-04:00',
          isDaytime: true,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 19,
          name: '',
          startTime: '2020-05-31T16:00:00-04:00',
          endTime: '2020-05-31T17:00:00-04:00',
          isDaytime: true,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 20,
          name: '',
          startTime: '2020-05-31T17:00:00-04:00',
          endTime: '2020-05-31T18:00:00-04:00',
          isDaytime: true,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 21,
          name: '',
          startTime: '2020-05-31T18:00:00-04:00',
          endTime: '2020-05-31T19:00:00-04:00',
          isDaytime: false,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 22,
          name: '',
          startTime: '2020-05-31T19:00:00-04:00',
          endTime: '2020-05-31T20:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 23,
          name: '',
          startTime: '2020-05-31T20:00:00-04:00',
          endTime: '2020-05-31T21:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 24,
          name: '',
          startTime: '2020-05-31T21:00:00-04:00',
          endTime: '2020-05-31T22:00:00-04:00',
          isDaytime: false,
          temperature: 64,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 25,
          name: '',
          startTime: '2020-05-31T22:00:00-04:00',
          endTime: '2020-05-31T23:00:00-04:00',
          isDaytime: false,
          temperature: 62,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '8 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 26,
          name: '',
          startTime: '2020-05-31T23:00:00-04:00',
          endTime: '2020-06-01T00:00:00-04:00',
          isDaytime: false,
          temperature: 60,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '7 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 27,
          name: '',
          startTime: '2020-06-01T00:00:00-04:00',
          endTime: '2020-06-01T01:00:00-04:00',
          isDaytime: false,
          temperature: 59,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '7 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 28,
          name: '',
          startTime: '2020-06-01T01:00:00-04:00',
          endTime: '2020-06-01T02:00:00-04:00',
          isDaytime: false,
          temperature: 57,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/skc?size=small',
          shortForecast: 'Clear',
          detailedForecast: '',
        },
        {
          number: 29,
          name: '',
          startTime: '2020-06-01T02:00:00-04:00',
          endTime: '2020-06-01T03:00:00-04:00',
          isDaytime: false,
          temperature: 56,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/skc?size=small',
          shortForecast: 'Clear',
          detailedForecast: '',
        },
        {
          number: 30,
          name: '',
          startTime: '2020-06-01T03:00:00-04:00',
          endTime: '2020-06-01T04:00:00-04:00',
          isDaytime: false,
          temperature: 54,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/skc?size=small',
          shortForecast: 'Clear',
          detailedForecast: '',
        },
        {
          number: 31,
          name: '',
          startTime: '2020-06-01T04:00:00-04:00',
          endTime: '2020-06-01T05:00:00-04:00',
          isDaytime: false,
          temperature: 52,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/skc?size=small',
          shortForecast: 'Clear',
          detailedForecast: '',
        },
        {
          number: 32,
          name: '',
          startTime: '2020-06-01T05:00:00-04:00',
          endTime: '2020-06-01T06:00:00-04:00',
          isDaytime: false,
          temperature: 52,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/skc?size=small',
          shortForecast: 'Clear',
          detailedForecast: '',
        },
        {
          number: 33,
          name: '',
          startTime: '2020-06-01T06:00:00-04:00',
          endTime: '2020-06-01T07:00:00-04:00',
          isDaytime: true,
          temperature: 53,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 34,
          name: '',
          startTime: '2020-06-01T07:00:00-04:00',
          endTime: '2020-06-01T08:00:00-04:00',
          isDaytime: true,
          temperature: 55,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 35,
          name: '',
          startTime: '2020-06-01T08:00:00-04:00',
          endTime: '2020-06-01T09:00:00-04:00',
          isDaytime: true,
          temperature: 58,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 36,
          name: '',
          startTime: '2020-06-01T09:00:00-04:00',
          endTime: '2020-06-01T10:00:00-04:00',
          isDaytime: true,
          temperature: 61,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 37,
          name: '',
          startTime: '2020-06-01T10:00:00-04:00',
          endTime: '2020-06-01T11:00:00-04:00',
          isDaytime: true,
          temperature: 64,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 38,
          name: '',
          startTime: '2020-06-01T11:00:00-04:00',
          endTime: '2020-06-01T12:00:00-04:00',
          isDaytime: true,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '7 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/skc?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 39,
          name: '',
          startTime: '2020-06-01T12:00:00-04:00',
          endTime: '2020-06-01T13:00:00-04:00',
          isDaytime: true,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '8 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 40,
          name: '',
          startTime: '2020-06-01T13:00:00-04:00',
          endTime: '2020-06-01T14:00:00-04:00',
          isDaytime: true,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 41,
          name: '',
          startTime: '2020-06-01T14:00:00-04:00',
          endTime: '2020-06-01T15:00:00-04:00',
          isDaytime: true,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 42,
          name: '',
          startTime: '2020-06-01T15:00:00-04:00',
          endTime: '2020-06-01T16:00:00-04:00',
          isDaytime: true,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 43,
          name: '',
          startTime: '2020-06-01T16:00:00-04:00',
          endTime: '2020-06-01T17:00:00-04:00',
          isDaytime: true,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 44,
          name: '',
          startTime: '2020-06-01T17:00:00-04:00',
          endTime: '2020-06-01T18:00:00-04:00',
          isDaytime: true,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '8 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=small',
          shortForecast: 'Sunny',
          detailedForecast: '',
        },
        {
          number: 45,
          name: '',
          startTime: '2020-06-01T18:00:00-04:00',
          endTime: '2020-06-01T19:00:00-04:00',
          isDaytime: false,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '7 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 46,
          name: '',
          startTime: '2020-06-01T19:00:00-04:00',
          endTime: '2020-06-01T20:00:00-04:00',
          isDaytime: false,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '7 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 47,
          name: '',
          startTime: '2020-06-01T20:00:00-04:00',
          endTime: '2020-06-01T21:00:00-04:00',
          isDaytime: false,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 48,
          name: '',
          startTime: '2020-06-01T21:00:00-04:00',
          endTime: '2020-06-01T22:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 49,
          name: '',
          startTime: '2020-06-01T22:00:00-04:00',
          endTime: '2020-06-01T23:00:00-04:00',
          isDaytime: false,
          temperature: 65,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 50,
          name: '',
          startTime: '2020-06-01T23:00:00-04:00',
          endTime: '2020-06-02T00:00:00-04:00',
          isDaytime: false,
          temperature: 62,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 51,
          name: '',
          startTime: '2020-06-02T00:00:00-04:00',
          endTime: '2020-06-02T01:00:00-04:00',
          isDaytime: false,
          temperature: 61,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=small',
          shortForecast: 'Mostly Clear',
          detailedForecast: '',
        },
        {
          number: 52,
          name: '',
          startTime: '2020-06-02T01:00:00-04:00',
          endTime: '2020-06-02T02:00:00-04:00',
          isDaytime: false,
          temperature: 60,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 53,
          name: '',
          startTime: '2020-06-02T02:00:00-04:00',
          endTime: '2020-06-02T03:00:00-04:00',
          isDaytime: false,
          temperature: 60,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 54,
          name: '',
          startTime: '2020-06-02T03:00:00-04:00',
          endTime: '2020-06-02T04:00:00-04:00',
          isDaytime: false,
          temperature: 59,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=small',
          shortForecast: 'Partly Cloudy',
          detailedForecast: '',
        },
        {
          number: 55,
          name: '',
          startTime: '2020-06-02T04:00:00-04:00',
          endTime: '2020-06-02T05:00:00-04:00',
          isDaytime: false,
          temperature: 58,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 56,
          name: '',
          startTime: '2020-06-02T05:00:00-04:00',
          endTime: '2020-06-02T06:00:00-04:00',
          isDaytime: false,
          temperature: 57,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 57,
          name: '',
          startTime: '2020-06-02T06:00:00-04:00',
          endTime: '2020-06-02T07:00:00-04:00',
          isDaytime: true,
          temperature: 57,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 58,
          name: '',
          startTime: '2020-06-02T07:00:00-04:00',
          endTime: '2020-06-02T08:00:00-04:00',
          isDaytime: true,
          temperature: 59,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 59,
          name: '',
          startTime: '2020-06-02T08:00:00-04:00',
          endTime: '2020-06-02T09:00:00-04:00',
          isDaytime: true,
          temperature: 60,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 60,
          name: '',
          startTime: '2020-06-02T09:00:00-04:00',
          endTime: '2020-06-02T10:00:00-04:00',
          isDaytime: true,
          temperature: 63,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 61,
          name: '',
          startTime: '2020-06-02T10:00:00-04:00',
          endTime: '2020-06-02T11:00:00-04:00',
          isDaytime: true,
          temperature: 65,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 62,
          name: '',
          startTime: '2020-06-02T11:00:00-04:00',
          endTime: '2020-06-02T12:00:00-04:00',
          isDaytime: true,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 63,
          name: '',
          startTime: '2020-06-02T12:00:00-04:00',
          endTime: '2020-06-02T13:00:00-04:00',
          isDaytime: true,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 64,
          name: '',
          startTime: '2020-06-02T13:00:00-04:00',
          endTime: '2020-06-02T14:00:00-04:00',
          isDaytime: true,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Partly Sunny',
          detailedForecast: '',
        },
        {
          number: 65,
          name: '',
          startTime: '2020-06-02T14:00:00-04:00',
          endTime: '2020-06-02T15:00:00-04:00',
          isDaytime: true,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Partly Sunny',
          detailedForecast: '',
        },
        {
          number: 66,
          name: '',
          startTime: '2020-06-02T15:00:00-04:00',
          endTime: '2020-06-02T16:00:00-04:00',
          isDaytime: true,
          temperature: 77,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Partly Sunny',
          detailedForecast: '',
        },
        {
          number: 67,
          name: '',
          startTime: '2020-06-02T16:00:00-04:00',
          endTime: '2020-06-02T17:00:00-04:00',
          isDaytime: true,
          temperature: 78,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Partly Sunny',
          detailedForecast: '',
        },
        {
          number: 68,
          name: '',
          startTime: '2020-06-02T17:00:00-04:00',
          endTime: '2020-06-02T18:00:00-04:00',
          isDaytime: true,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 69,
          name: '',
          startTime: '2020-06-02T18:00:00-04:00',
          endTime: '2020-06-02T19:00:00-04:00',
          isDaytime: false,
          temperature: 78,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 70,
          name: '',
          startTime: '2020-06-02T19:00:00-04:00',
          endTime: '2020-06-02T20:00:00-04:00',
          isDaytime: false,
          temperature: 77,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/bkn?size=small',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: '',
        },
        {
          number: 71,
          name: '',
          startTime: '2020-06-02T20:00:00-04:00',
          endTime: '2020-06-02T21:00:00-04:00',
          isDaytime: false,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 72,
          name: '',
          startTime: '2020-06-02T21:00:00-04:00',
          endTime: '2020-06-02T22:00:00-04:00',
          isDaytime: false,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 73,
          name: '',
          startTime: '2020-06-02T22:00:00-04:00',
          endTime: '2020-06-02T23:00:00-04:00',
          isDaytime: false,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 74,
          name: '',
          startTime: '2020-06-02T23:00:00-04:00',
          endTime: '2020-06-03T00:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 75,
          name: '',
          startTime: '2020-06-03T00:00:00-04:00',
          endTime: '2020-06-03T01:00:00-04:00',
          isDaytime: false,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 76,
          name: '',
          startTime: '2020-06-03T01:00:00-04:00',
          endTime: '2020-06-03T02:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 77,
          name: '',
          startTime: '2020-06-03T02:00:00-04:00',
          endTime: '2020-06-03T03:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 78,
          name: '',
          startTime: '2020-06-03T03:00:00-04:00',
          endTime: '2020-06-03T04:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 79,
          name: '',
          startTime: '2020-06-03T04:00:00-04:00',
          endTime: '2020-06-03T05:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 80,
          name: '',
          startTime: '2020-06-03T05:00:00-04:00',
          endTime: '2020-06-03T06:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 81,
          name: '',
          startTime: '2020-06-03T06:00:00-04:00',
          endTime: '2020-06-03T07:00:00-04:00',
          isDaytime: true,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 82,
          name: '',
          startTime: '2020-06-03T07:00:00-04:00',
          endTime: '2020-06-03T08:00:00-04:00',
          isDaytime: true,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 83,
          name: '',
          startTime: '2020-06-03T08:00:00-04:00',
          endTime: '2020-06-03T09:00:00-04:00',
          isDaytime: true,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 84,
          name: '',
          startTime: '2020-06-03T09:00:00-04:00',
          endTime: '2020-06-03T10:00:00-04:00',
          isDaytime: true,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 85,
          name: '',
          startTime: '2020-06-03T10:00:00-04:00',
          endTime: '2020-06-03T11:00:00-04:00',
          isDaytime: true,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 86,
          name: '',
          startTime: '2020-06-03T11:00:00-04:00',
          endTime: '2020-06-03T12:00:00-04:00',
          isDaytime: true,
          temperature: 82,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 87,
          name: '',
          startTime: '2020-06-03T12:00:00-04:00',
          endTime: '2020-06-03T13:00:00-04:00',
          isDaytime: true,
          temperature: 85,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 88,
          name: '',
          startTime: '2020-06-03T13:00:00-04:00',
          endTime: '2020-06-03T14:00:00-04:00',
          isDaytime: true,
          temperature: 87,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 89,
          name: '',
          startTime: '2020-06-03T14:00:00-04:00',
          endTime: '2020-06-03T15:00:00-04:00',
          isDaytime: true,
          temperature: 89,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 90,
          name: '',
          startTime: '2020-06-03T15:00:00-04:00',
          endTime: '2020-06-03T16:00:00-04:00',
          isDaytime: true,
          temperature: 90,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '6 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 91,
          name: '',
          startTime: '2020-06-03T16:00:00-04:00',
          endTime: '2020-06-03T17:00:00-04:00',
          isDaytime: true,
          temperature: 91,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 92,
          name: '',
          startTime: '2020-06-03T17:00:00-04:00',
          endTime: '2020-06-03T18:00:00-04:00',
          isDaytime: true,
          temperature: 90,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 93,
          name: '',
          startTime: '2020-06-03T18:00:00-04:00',
          endTime: '2020-06-03T19:00:00-04:00',
          isDaytime: false,
          temperature: 89,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 94,
          name: '',
          startTime: '2020-06-03T19:00:00-04:00',
          endTime: '2020-06-03T20:00:00-04:00',
          isDaytime: false,
          temperature: 87,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 95,
          name: '',
          startTime: '2020-06-03T20:00:00-04:00',
          endTime: '2020-06-03T21:00:00-04:00',
          isDaytime: false,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 96,
          name: '',
          startTime: '2020-06-03T21:00:00-04:00',
          endTime: '2020-06-03T22:00:00-04:00',
          isDaytime: false,
          temperature: 81,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 97,
          name: '',
          startTime: '2020-06-03T22:00:00-04:00',
          endTime: '2020-06-03T23:00:00-04:00',
          isDaytime: false,
          temperature: 78,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 98,
          name: '',
          startTime: '2020-06-03T23:00:00-04:00',
          endTime: '2020-06-04T00:00:00-04:00',
          isDaytime: false,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 99,
          name: '',
          startTime: '2020-06-04T00:00:00-04:00',
          endTime: '2020-06-04T01:00:00-04:00',
          isDaytime: false,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 100,
          name: '',
          startTime: '2020-06-04T01:00:00-04:00',
          endTime: '2020-06-04T02:00:00-04:00',
          isDaytime: false,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 101,
          name: '',
          startTime: '2020-06-04T02:00:00-04:00',
          endTime: '2020-06-04T03:00:00-04:00',
          isDaytime: false,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 102,
          name: '',
          startTime: '2020-06-04T03:00:00-04:00',
          endTime: '2020-06-04T04:00:00-04:00',
          isDaytime: false,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 103,
          name: '',
          startTime: '2020-06-04T04:00:00-04:00',
          endTime: '2020-06-04T05:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 104,
          name: '',
          startTime: '2020-06-04T05:00:00-04:00',
          endTime: '2020-06-04T06:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 105,
          name: '',
          startTime: '2020-06-04T06:00:00-04:00',
          endTime: '2020-06-04T07:00:00-04:00',
          isDaytime: true,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 106,
          name: '',
          startTime: '2020-06-04T07:00:00-04:00',
          endTime: '2020-06-04T08:00:00-04:00',
          isDaytime: true,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 107,
          name: '',
          startTime: '2020-06-04T08:00:00-04:00',
          endTime: '2020-06-04T09:00:00-04:00',
          isDaytime: true,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 108,
          name: '',
          startTime: '2020-06-04T09:00:00-04:00',
          endTime: '2020-06-04T10:00:00-04:00',
          isDaytime: true,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 109,
          name: '',
          startTime: '2020-06-04T10:00:00-04:00',
          endTime: '2020-06-04T11:00:00-04:00',
          isDaytime: true,
          temperature: 77,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 110,
          name: '',
          startTime: '2020-06-04T11:00:00-04:00',
          endTime: '2020-06-04T12:00:00-04:00',
          isDaytime: true,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 111,
          name: '',
          startTime: '2020-06-04T12:00:00-04:00',
          endTime: '2020-06-04T13:00:00-04:00',
          isDaytime: true,
          temperature: 81,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 112,
          name: '',
          startTime: '2020-06-04T13:00:00-04:00',
          endTime: '2020-06-04T14:00:00-04:00',
          isDaytime: true,
          temperature: 83,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 113,
          name: '',
          startTime: '2020-06-04T14:00:00-04:00',
          endTime: '2020-06-04T15:00:00-04:00',
          isDaytime: true,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 114,
          name: '',
          startTime: '2020-06-04T15:00:00-04:00',
          endTime: '2020-06-04T16:00:00-04:00',
          isDaytime: true,
          temperature: 85,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 115,
          name: '',
          startTime: '2020-06-04T16:00:00-04:00',
          endTime: '2020-06-04T17:00:00-04:00',
          isDaytime: true,
          temperature: 85,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 116,
          name: '',
          startTime: '2020-06-04T17:00:00-04:00',
          endTime: '2020-06-04T18:00:00-04:00',
          isDaytime: true,
          temperature: 85,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 117,
          name: '',
          startTime: '2020-06-04T18:00:00-04:00',
          endTime: '2020-06-04T19:00:00-04:00',
          isDaytime: false,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 118,
          name: '',
          startTime: '2020-06-04T19:00:00-04:00',
          endTime: '2020-06-04T20:00:00-04:00',
          isDaytime: false,
          temperature: 83,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 119,
          name: '',
          startTime: '2020-06-04T20:00:00-04:00',
          endTime: '2020-06-04T21:00:00-04:00',
          isDaytime: false,
          temperature: 81,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 120,
          name: '',
          startTime: '2020-06-04T21:00:00-04:00',
          endTime: '2020-06-04T22:00:00-04:00',
          isDaytime: false,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 121,
          name: '',
          startTime: '2020-06-04T22:00:00-04:00',
          endTime: '2020-06-04T23:00:00-04:00',
          isDaytime: false,
          temperature: 76,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 122,
          name: '',
          startTime: '2020-06-04T23:00:00-04:00',
          endTime: '2020-06-05T00:00:00-04:00',
          isDaytime: false,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 123,
          name: '',
          startTime: '2020-06-05T00:00:00-04:00',
          endTime: '2020-06-05T01:00:00-04:00',
          isDaytime: false,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 124,
          name: '',
          startTime: '2020-06-05T01:00:00-04:00',
          endTime: '2020-06-05T02:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 125,
          name: '',
          startTime: '2020-06-05T02:00:00-04:00',
          endTime: '2020-06-05T03:00:00-04:00',
          isDaytime: false,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 126,
          name: '',
          startTime: '2020-06-05T03:00:00-04:00',
          endTime: '2020-06-05T04:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 127,
          name: '',
          startTime: '2020-06-05T04:00:00-04:00',
          endTime: '2020-06-05T05:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 128,
          name: '',
          startTime: '2020-06-05T05:00:00-04:00',
          endTime: '2020-06-05T06:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 129,
          name: '',
          startTime: '2020-06-05T06:00:00-04:00',
          endTime: '2020-06-05T07:00:00-04:00',
          isDaytime: true,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 130,
          name: '',
          startTime: '2020-06-05T07:00:00-04:00',
          endTime: '2020-06-05T08:00:00-04:00',
          isDaytime: true,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 131,
          name: '',
          startTime: '2020-06-05T08:00:00-04:00',
          endTime: '2020-06-05T09:00:00-04:00',
          isDaytime: true,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 132,
          name: '',
          startTime: '2020-06-05T09:00:00-04:00',
          endTime: '2020-06-05T10:00:00-04:00',
          isDaytime: true,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 133,
          name: '',
          startTime: '2020-06-05T10:00:00-04:00',
          endTime: '2020-06-05T11:00:00-04:00',
          isDaytime: true,
          temperature: 75,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'NE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 134,
          name: '',
          startTime: '2020-06-05T11:00:00-04:00',
          endTime: '2020-06-05T12:00:00-04:00',
          isDaytime: true,
          temperature: 78,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'NE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 135,
          name: '',
          startTime: '2020-06-05T12:00:00-04:00',
          endTime: '2020-06-05T13:00:00-04:00',
          isDaytime: true,
          temperature: 80,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'NE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 136,
          name: '',
          startTime: '2020-06-05T13:00:00-04:00',
          endTime: '2020-06-05T14:00:00-04:00',
          isDaytime: true,
          temperature: 82,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'E',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 137,
          name: '',
          startTime: '2020-06-05T14:00:00-04:00',
          endTime: '2020-06-05T15:00:00-04:00',
          isDaytime: true,
          temperature: 83,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'E',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 138,
          name: '',
          startTime: '2020-06-05T15:00:00-04:00',
          endTime: '2020-06-05T16:00:00-04:00',
          isDaytime: true,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'E',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 139,
          name: '',
          startTime: '2020-06-05T16:00:00-04:00',
          endTime: '2020-06-05T17:00:00-04:00',
          isDaytime: true,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 140,
          name: '',
          startTime: '2020-06-05T17:00:00-04:00',
          endTime: '2020-06-05T18:00:00-04:00',
          isDaytime: true,
          temperature: 84,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 141,
          name: '',
          startTime: '2020-06-05T18:00:00-04:00',
          endTime: '2020-06-05T19:00:00-04:00',
          isDaytime: false,
          temperature: 83,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 142,
          name: '',
          startTime: '2020-06-05T19:00:00-04:00',
          endTime: '2020-06-05T20:00:00-04:00',
          isDaytime: false,
          temperature: 81,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 143,
          name: '',
          startTime: '2020-06-05T20:00:00-04:00',
          endTime: '2020-06-05T21:00:00-04:00',
          isDaytime: false,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 144,
          name: '',
          startTime: '2020-06-05T21:00:00-04:00',
          endTime: '2020-06-05T22:00:00-04:00',
          isDaytime: false,
          temperature: 77,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'SE',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 145,
          name: '',
          startTime: '2020-06-05T22:00:00-04:00',
          endTime: '2020-06-05T23:00:00-04:00',
          isDaytime: false,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 146,
          name: '',
          startTime: '2020-06-05T23:00:00-04:00',
          endTime: '2020-06-06T00:00:00-04:00',
          isDaytime: false,
          temperature: 72,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 147,
          name: '',
          startTime: '2020-06-06T00:00:00-04:00',
          endTime: '2020-06-06T01:00:00-04:00',
          isDaytime: false,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 148,
          name: '',
          startTime: '2020-06-06T01:00:00-04:00',
          endTime: '2020-06-06T02:00:00-04:00',
          isDaytime: false,
          temperature: 70,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 149,
          name: '',
          startTime: '2020-06-06T02:00:00-04:00',
          endTime: '2020-06-06T03:00:00-04:00',
          isDaytime: false,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 150,
          name: '',
          startTime: '2020-06-06T03:00:00-04:00',
          endTime: '2020-06-06T04:00:00-04:00',
          isDaytime: false,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 151,
          name: '',
          startTime: '2020-06-06T04:00:00-04:00',
          endTime: '2020-06-06T05:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 152,
          name: '',
          startTime: '2020-06-06T05:00:00-04:00',
          endTime: '2020-06-06T06:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 153,
          name: '',
          startTime: '2020-06-06T06:00:00-04:00',
          endTime: '2020-06-06T07:00:00-04:00',
          isDaytime: true,
          temperature: 68,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 154,
          name: '',
          startTime: '2020-06-06T07:00:00-04:00',
          endTime: '2020-06-06T08:00:00-04:00',
          isDaytime: true,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 155,
          name: '',
          startTime: '2020-06-06T08:00:00-04:00',
          endTime: '2020-06-06T09:00:00-04:00',
          isDaytime: true,
          temperature: 71,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
        {
          number: 156,
          name: '',
          startTime: '2020-06-06T09:00:00-04:00',
          endTime: '2020-06-06T10:00:00-04:00',
          isDaytime: true,
          temperature: 73,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '1 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=small',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast: '',
        },
      ],
    },
  },
  daily: {
    '@context': [
      'https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld',
      {
        wx: 'https://api.weather.gov/ontology#',
        geo: 'http://www.opengis.net/ont/geosparql#',
        unit: 'http://codes.wmo.int/common/unit/',
        '@vocab': 'https://api.weather.gov/ontology#',
      },
    ],
    type: 'Feature',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'Point',
          coordinates: [-77.024773199999998, 38.888346400000003],
        },
        {
          type: 'Polygon',
          coordinates: [
            [
              [-77.036997299999996, 38.900782700000001],
              [-77.040754800000002, 38.878836499999998],
              [-77.012551900000005, 38.875908500000001],
              [-77.008788700000011, 38.8978544],
              [-77.036997299999996, 38.900782700000001],
            ],
          ],
        },
      ],
    },
    properties: {
      updated: '2020-05-30T23:32:01+00:00',
      units: 'us',
      forecastGenerator: 'BaselineForecastGenerator',
      generatedAt: '2020-05-31T02:30:28+00:00',
      updateTime: '2020-05-30T23:32:01+00:00',
      validTimes: '2020-05-30T17:00:00+00:00/P7DT8H',
      elevation: {
        value: 6.0960000000000001,
        unitCode: 'unit:m',
      },
      periods: [
        {
          number: 1,
          name: 'Tonight',
          startTime: '2020-05-30T22:00:00-04:00',
          endTime: '2020-05-31T06:00:00-04:00',
          isDaytime: false,
          temperature: 58,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '10 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
          shortForecast: 'Mostly Clear',
          detailedForecast:
            'Mostly clear, with a low around 58. Northwest wind around 10 mph.',
        },
        {
          number: 2,
          name: 'Sunday',
          startTime: '2020-05-31T06:00:00-04:00',
          endTime: '2020-05-31T18:00:00-04:00',
          isDaytime: true,
          temperature: 74,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/day/few?size=medium',
          shortForecast: 'Sunny',
          detailedForecast:
            'Sunny, with a high near 74. North wind around 12 mph, with gusts as high as 18 mph.',
        },
        {
          number: 3,
          name: 'Sunday Night',
          startTime: '2020-05-31T18:00:00-04:00',
          endTime: '2020-06-01T06:00:00-04:00',
          isDaytime: false,
          temperature: 51,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 to 12 mph',
          windDirection: 'N',
          icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
          shortForecast: 'Mostly Clear',
          detailedForecast:
            'Mostly clear, with a low around 51. North wind 5 to 12 mph.',
        },
        {
          number: 4,
          name: 'Monday',
          startTime: '2020-06-01T06:00:00-04:00',
          endTime: '2020-06-01T18:00:00-04:00',
          isDaytime: true,
          temperature: 76,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '5 to 9 mph',
          windDirection: 'NW',
          icon: 'https://api.weather.gov/icons/land/day/few?size=medium',
          shortForecast: 'Sunny',
          detailedForecast:
            'Sunny, with a high near 76. Northwest wind 5 to 9 mph.',
        },
        {
          number: 5,
          name: 'Monday Night',
          startTime: '2020-06-01T18:00:00-04:00',
          endTime: '2020-06-02T06:00:00-04:00',
          isDaytime: false,
          temperature: 57,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 to 7 mph',
          windDirection: 'W',
          icon: 'https://api.weather.gov/icons/land/night/sct?size=medium',
          shortForecast: 'Partly Cloudy',
          detailedForecast:
            'Partly cloudy, with a low around 57. West wind 2 to 7 mph.',
        },
        {
          number: 6,
          name: 'Tuesday',
          startTime: '2020-06-02T06:00:00-04:00',
          endTime: '2020-06-02T18:00:00-04:00',
          isDaytime: true,
          temperature: 79,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 to 3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/bkn?size=medium',
          shortForecast: 'Mostly Cloudy',
          detailedForecast: 'Mostly cloudy, with a high near 79.',
        },
        {
          number: 7,
          name: 'Tuesday Night',
          startTime: '2020-06-02T18:00:00-04:00',
          endTime: '2020-06-03T06:00:00-04:00',
          isDaytime: false,
          temperature: 66,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'SW',
          icon:
            'https://api.weather.gov/icons/land/night/tsra_sct,30?size=medium',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms after 8pm. Mostly cloudy, with a low around 66. Chance of precipitation is 30%.',
        },
        {
          number: 8,
          name: 'Wednesday',
          startTime: '2020-06-03T06:00:00-04:00',
          endTime: '2020-06-03T18:00:00-04:00',
          isDaytime: true,
          temperature: 91,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 to 6 mph',
          windDirection: 'W',
          icon:
            'https://api.weather.gov/icons/land/day/tsra_hi,30/tsra_hi?size=medium',
          shortForecast:
            'Chance Showers And Thunderstorms then Slight Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms before 8am, then a slight chance of showers and thunderstorms. Mostly sunny, with a high near 91. Chance of precipitation is 30%.',
        },
        {
          number: 9,
          name: 'Wednesday Night',
          startTime: '2020-06-03T18:00:00-04:00',
          endTime: '2020-06-04T06:00:00-04:00',
          isDaytime: false,
          temperature: 69,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon:
            'https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms. Mostly cloudy, with a low around 69. Chance of precipitation is 30%.',
        },
        {
          number: 10,
          name: 'Thursday',
          startTime: '2020-06-04T06:00:00-04:00',
          endTime: '2020-06-04T18:00:00-04:00',
          isDaytime: true,
          temperature: 88,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '3 mph',
          windDirection: 'W',
          icon:
            'https://api.weather.gov/icons/land/day/tsra_sct,30?size=medium',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms. Mostly cloudy, with a high near 88. Chance of precipitation is 30%.',
        },
        {
          number: 11,
          name: 'Thursday Night',
          startTime: '2020-06-04T18:00:00-04:00',
          endTime: '2020-06-05T06:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'NW',
          icon:
            'https://api.weather.gov/icons/land/night/tsra_hi,30/tsra_hi?size=medium',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms. Mostly cloudy, with a low around 67. Chance of precipitation is 30%.',
        },
        {
          number: 12,
          name: 'Friday',
          startTime: '2020-06-05T06:00:00-04:00',
          endTime: '2020-06-05T18:00:00-04:00',
          isDaytime: true,
          temperature: 86,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'NE',
          icon: 'https://api.weather.gov/icons/land/day/tsra_sct?size=medium',
          shortForecast: 'Chance Showers And Thunderstorms',
          detailedForecast:
            'A chance of showers and thunderstorms. Partly sunny, with a high near 86.',
        },
        {
          number: 13,
          name: 'Friday Night',
          startTime: '2020-06-05T18:00:00-04:00',
          endTime: '2020-06-06T06:00:00-04:00',
          isDaytime: false,
          temperature: 67,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '2 mph',
          windDirection: 'S',
          icon: 'https://api.weather.gov/icons/land/night/tsra_hi?size=medium',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast:
            'A slight chance of showers and thunderstorms. Partly cloudy, with a low around 67.',
        },
        {
          number: 14,
          name: 'Saturday',
          startTime: '2020-06-06T06:00:00-04:00',
          endTime: '2020-06-06T18:00:00-04:00',
          isDaytime: true,
          temperature: 88,
          temperatureUnit: 'F',
          temperatureTrend: null,
          windSpeed: '0 to 3 mph',
          windDirection: 'SW',
          icon: 'https://api.weather.gov/icons/land/day/tsra_hi?size=medium',
          shortForecast: 'Slight Chance Showers And Thunderstorms',
          detailedForecast:
            'A slight chance of showers and thunderstorms. Mostly sunny, with a high near 88.',
        },
      ],
    },
  },
};
